app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  pg_url: postgresql://user:pass@localhost:5432/postgres
  pool_max: 2

detector:
  host: 'http://192.168.1.9:5000/v1/object-detection/yolov5'
  form_field: 'image'
  form_name: 'accumulator.jpg'

telegram:
  bot_token: '6053825271:AAEANkoVpXg1cz5bCvDrm7iK0xiMDOqQHiY'